### ISSUE TITLE
Change from the connection method

### ISSUE THREAD

**Issue by PrivatHomeServer** [ioBroker/ioBroker.hass#1]
Hass.io has a few months the system of username and password. (or oauth) This is currently not available in the adapter.

https://www.home-assistant.io/docs/authentication/

With an older hass.io installion everything works great.

**Comment by Alexalex89** [comment]
I just opened a pull request. I modified the auth method to use Long-Lived Access Tokens.

**Comment by alexalex89** [comment]
Merged and fixed!

**Comment by PrivatHomeServer** [comment]
I will check it later... Sounds great.

**Comment by d3frost** [comment]
> I just opened a pull request. I modified the auth method to use Long-Lived Access Tokens.

can you tell a non Progammer how you do this ?

**Comment by alexalex89** [comment]
> > I just opened a pull request. I modified the auth method to use Long-Lived Access Tokens.
> 
> can you tell a non Progammer how you do this ?

You don't have to change anything. It's been fixed and should be available in the latest version.

**Comment by GermanBluefox** [comment]
https://github.com/ioBroker/ioBroker.hass/issues/6#issuecomment-623997485
