### ISSUE TITLE
Не подключается к hass

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.hass#10]
**Describe the bug**  
Не подключается
нет поля для ввода логина, только пароль
кнопки сохранить и сохранить и выйти не стандартного вида, случайно получилось нажать сохранить.

**Screenshots & Logfiles**  

host.iobroker | 2020-12-16 03:07:08.849 | info | Restart adapter system.adapter.hass.0 because enabled
-- | -- | -- | --
host.iobroker | 2020-12-16 03:07:08.849 | error | instance system.adapter.hass.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker | 2020-12-16 03:07:08.848 | error | Caught by controller[0]: at internal/main/run_main_module.js:17:47
host.iobroker | 2020-12-16 03:07:08.848 | error | Caught by controller[0]: at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
host.iobroker | 2020-12-16 03:07:08.848 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:708:14)
host.iobroker | 2020-12-16 03:07:08.848 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:863:32)
host.iobroker | 2020-12-16 03:07:08.848 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
host.iobroker | 2020-12-16 03:07:08.847 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:999:30)
host.iobroker | 2020-12-16 03:07:08.847 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.hass/main.js:399:5)
host.iobroker | 2020-12-16 03:07:08.847 | error | Caught by controller[0]: at startAdapter (/opt/iobroker/node_modules/iobroker.hass/main.js:18:56)
host.iobroker | 2020-12-16 03:07:08.847 | error | Caught by controller[0]: ReferenceError: stop is not defined
host.iobroker | 2020-12-16 03:07:08.846 | error | Caught by controller[0]: ^
host.iobroker | 2020-12-16 03:07:08.846 | error | Caught by controller[0]: Object.assign(options, {name: adapterName, unload: stop});
host.iobroker | 2020-12-16 03:07:08.846 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.hass/main.js:18
host.iobroker | 2020-12-16 03:07:08.576 | info | instance system.adapter.hass.0 started with pid 17436

![image](https://user-images.githubusercontent.com/37106885/102287898-718c0c00-3f4c-11eb-943c-b54666df3f44.png)

**Versions:**  
 - Adapter version: 1.0.0
 - JS-Controller version: 3.1.6
 - Node version: 12.20.0
 - Operating system: docker 5.1.0
 - Home Assistant 2020.12.0
 - Версия Python | 3.8.6
-- | --

**Additional context**

**Comment by spencerbutler** [comment]
I am seeing the same thing on a fresh install. Does anyone have any insight into this?
