### ISSUE TITLE
need current js version (v12 is in addon). Needed: v16

### ISSUE THREAD

**Issue by gerhardvilsecker** [ioBroker/ioBroker.hass#102]
Hey guys,
I currently try to integrate gruenbeck water desalting equipment to ha. Therefore I have to install MQTTT Client in iobroker provided by iobroker.hass addon. MQTT client installation fails with errormessage: nodjs version v16 required v12 is installed.
Is it possible to uddate nodejs version inside of your container?

Thx and regards

Gerhard

**Comment by Apollon77** [comment]
Hm ... are you sure this issue is correct here? if you have issues with the ipbroker docker container please check the documentation there. This plugin should not have anything to do with it. maybe you just need to upgrade the container?

**Comment by gerhardvilsecker** [comment]
Yes I already tried by adding eval "iobroker update && iobroker upgrade self" to options section in iobroker.hass addon configuration. However this ends up in an unstartable addon. errormessages during upgrade:
Update js-controller from @3.2.16 to @5.0.17
NPM version: 6.14.11
npm install iobroker.js-controller@5.0.17 --loglevel error --unsafe-perm --prefix "/data/iobroker" (System call)
In file included from ../node_modules/nan/nan.h:62,
                 from ../src/main.cpp:3:
/opt/iobroker/.cache/node-gyp/12.21.0/include/node/node.h:737:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/opt/iobroker/.cache/node-gyp/12.21.0/include/node/node.h:771:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/main.cpp:42:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(diskusage, Init)
 ^~~~~~~~~~~
In file included from ../node_modules/nan/nan.h:62,
                 from ../src/unix_dgram.cc:5:
/opt/iobroker/.cache/node-gyp/12.21.0/include/node/node.h:737:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/opt/iobroker/.cache/node-gyp/12.21.0/include/node/node.h:771:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/unix_dgram.cc:404:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(unix_dgram, Initialize)
 ^~~~~~~~~~~
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:timers/promises'
Require stack:
- /data/iobroker/node_modules/@iobroker/js-controller-cli/build/lib/setup/dbConnection.js
- /data/iobroker/node_modules/@iobroker/js-controller-cli/build/lib/setup.js
- /data/iobroker/node_modules/@iobroker/js-controller-cli/build/index.js
- /data/iobroker/node_modules/iobroker.js-controller/iobroker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/data/iobroker/node_modules/@iobroker/js-controller-cli/build/lib/setup/dbConnection.js:34:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/data/iobroker/node_modules/@iobroker/js-controller-cli/build/lib/setup/dbConnection.js',
    '/data/iobroker/node_modules/@iobroker/js-controller-cli/build/lib/setup.js',
    '/data/iobroker/node_modules/@iobroker/js-controller-cli/build/index.js',
    '/data/iobroker/node_modules/iobroker.js-controller/iobroker.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iobroker.js-controller@5.0.17 install: `node iobroker.js setup first`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iobroker.js-controller@5.0.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/iobroker/.npm/_logs/2024-01-30T18_05_42_650Z-debug.log
host.1e14b3fb-iobroker Cannot install iobroker.js-controller@5.0.17: 1
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/data/iobroker/node_modules/iobroker.js-controller/controller.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

**Comment by Apollon77** [comment]
The Node.js version is bound to the version of the Docker container you use!! So please update the container version!
