### ISSUE TITLE
Please mark project as abandoned

### ISSUE THREAD

**Issue by DarkFox** [ioBroker/ioBroker.hass#16]
With no updates for 8 months, and the adapter not working on the current version, it'd be nice of you to make people aware that it is abandoned, and they shouldn't waste their time with it.

**Comment by Apollon77** [comment]
Hm ... Can you go more into detail please? or is it about issue #9 ? You saw the workaround described there with the 0.1.0 fork that works? Yes we need to adjust the 1.0 ... 
222 installations of 1.0.0 are out there ... and roughly 9 users commented on that one issue ... I close this as duplicate to #9 Please open new issue with more details if it is NOT that
