### ISSUE TITLE
Error: connect EHOSTUNREACH

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.hass#32]
**Describe the bug**  
HA is installed in a docker container, in host mode. Iobroker is also in a container, but in a VLAN. I created a token, I'm trying to connect - I get an error Error: connect EHOSTUNREACH 192.168.88.18:8123

**Versions:**  
 - Adapter version: 1.0.1
 - JS-Controller version: 3.3.18
 - Node version: <node-version> v12.22.5
 - Operating system: doicker

**Comment by Apollon77** [comment]
EHOSTUNREACH is a usual network error and means that the nodejs process can not reach this IP itself via network ... please check availability
