### ISSUE TITLE
Since v1.1.0 password is in clear text

### ISSUE THREAD

**Issue by thost96** [ioBroker/ioBroker.hass#44]
**Describe the bug**  
Since updating this adapter to v1.1.0 today, the password in the admin UI is always shows as clear text. Other adapters display this as **** as this should not be clearly visible. 

![image](https://user-images.githubusercontent.com/5551251/160082117-5c8c1c43-e568-411a-a8b2-ab05ec5f22d1.png)

* Adapter Version 1.1.0
* js-controller 4.0.21 
* Host OS Ubuntu

**Comment by Apollon77** [comment]
Fixed on Github, 1.1.1 coming on npm too in parallel. Thank you
