### ISSUE TITLE
User ist missing

### ISSUE THREAD

**Issue by ralfm12** [ioBroker/ioBroker.hass#6]
I have tried this adapter. There ist a Textfield for the password, but not for the username.
So the connect to Homeassistant fails.
(3432) Invalid answer: {"type": "auth_invalid", "message": "Invalid access token or password"}

**Comment by Tscherno** [comment]
Same issue. No authentication possible with that adaptor.

**Comment by lighu36** [comment]
好像没有更新了

**Comment by KarlKiel** [comment]
Create a long term token in HASS and use it as PW (copy it also in the repeat field)
