### ISSUE TITLE
Invalid access token or password

### ISSUE THREAD

**Issue by nikmaier** [ioBroker/ioBroker.hass#80]
Hallo,
ich habe den Longlive Token in meiner Homeassist Installation erstellt:

![image](https://github.com/ioBroker/ioBroker.hass/assets/69574329/d0d61389-3d5e-4b38-bb42-810252441cd3)

Diesen habe ich dann unter Passwort zweimal eingefügt.
IP und Port stimmt auch in der Instanz:

![image](https://github.com/ioBroker/ioBroker.hass/assets/69574329/69f25214-75a0-461d-b937-dec71e111953)

Bekomme aber trotzdem diese Meldung im Log:

![image](https://github.com/ioBroker/ioBroker.hass/assets/69574329/ca4ee37b-fea4-42f2-8efa-d5c6552742e9)

Was mache ich da falsch?

**Comment by Apollon77** [comment]
Gute Frage ... Vllt die Frage auch mal im Forum stellen? Vllt da mal nach passenden Threads suchen wo Leute sind die den Adapter nutzen

**Comment by nikmaier** [comment]
Hab meinen eigenen Fehler gefunden:

Ich habe den Token nicht komplett kopiert, sondern ich dachte es sei alles markiert, war es aber nicht  :-)
